package slider

import com.microsoft.playwright.Browser
import com.microsoft.playwright.BrowserContext
import com.microsoft.playwright.Page
import com.microsoft.playwright.Playwright
import java.net.HttpURLConnection
import java.net.URI
import java.nio.file.Path
import java.util.concurrent.TimeUnit

/**
 * Shared Playwright lifecycle and HTTP server support for visual tests
 * that validate pre-generated Reveal.js HTML fixtures.
 *
 * Decoupling rationale (session 034):
 * - The HTML is generated by the root project's `asciidoctorRevealJs` task
 *   (real Gradle home, JRuby gem present) and committed/copied as a fixture.
 * - The tests only render the fixture in a headless browser — no GradleRunner,
 *   no isolated JRuby, no `withGradleUserHomeDir` needed.
 *
 * Usage in a `@TestInstance(PER_CLASS)` test:
 * ```
 * private val support = PlaywrightFixtureSupport()
 *
 * @BeforeAll  fun launch()  = support.launchBrowser()
 * @AfterAll   fun close()   = support.closeBrowser()
 *
 * @Test fun test() {
 *     support.withPage(fixtureHtmlPath) { page ->
 *         // assertions on page
 *     }
 * }
 * ```
 */
class PlaywrightFixtureSupport {

    private lateinit var playwright: Playwright
    private lateinit var browser: Browser

    fun launchBrowser() {
        playwright = Playwright.create()
        browser = playwright.chromium().launch(
            com.microsoft.playwright.BrowserType.LaunchOptions()
                .setHeadless(true)
                .setArgs(listOf("--no-sandbox", "--disable-gpu"))
        )
    }

    fun closeBrowser() {
        browser.close()
        playwright.close()
    }

    /**
     * Starts `npx serve` on [port] serving [serveRoot], waits up to 15s
     * for an HTTP 200 response, then executes [block] with a fresh page
     * navigating to `http://localhost:$port/[relativePath]`.
     *
     * The HTTP server and browser context are always cleaned up in `finally`.
     */
    fun withPage(
        serveRoot: Path,
        relativePath: String,
        port: Int = 4335,
        block: (Page) -> Unit,
    ) {
        val server = startHttpServer(serveRoot, port)
        var context: BrowserContext? = null
        try {
            context = browser.newContext()
            val page = context.newPage()
            val url = "http://localhost:$port/$relativePath"
            page.navigate(url)
            page.waitForSelector(".reveal .slides")
            block(page)
        } finally {
            context?.close()
            server.destroyForcibly()
            server.waitFor(5, TimeUnit.SECONDS)
        }
    }

    private fun startHttpServer(serveRoot: Path, port: Int = 4335): Process {
        val process = ProcessBuilder(
            "python3", "-m", "http.server", port.toString(),
            "--directory", serveRoot.toAbsolutePath().toString()
        )
            .redirectErrorStream(true)
            .start()

        val deadline = System.currentTimeMillis() + 15_000
        val url = URI("http://localhost:$port").toURL()
        while (System.currentTimeMillis() < deadline) {
            if (!process.isAlive) {
                val stderr = process.inputStream.bufferedReader().readText()
                throw RuntimeException("http.server exited prematurely: $stderr")
            }
            try {
                val conn = url.openConnection() as HttpURLConnection
                conn.connectTimeout = 500
                conn.readTimeout = 500
                conn.requestMethod = "GET"
                if (conn.responseCode in 200..399) {
                    return process
                }
            } catch (_: Exception) {
            }
            Thread.sleep(500)
        }
        process.destroyForcibly()
        throw RuntimeException("http.server did not respond within 15s on port $port")
    }
}