package slider

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import slider.rtl.RtlSlideAssertion
import slider.rtl.SlideRenderData
import java.nio.file.Files
import java.nio.file.Path

/**
 * Playwright-jvm functional test validating that a Reveal.js deck generated
 * with RTL mode (`:revealjs_direction: rtl`) renders in Right-To-Left layout.
 *
 * Architecture (session 034):
 * The HTML fixture is pre-generated by the root project's `asciidoctorRevealJs`
 * task (real Gradle home, JRuby gem present). The Arabic demo deck
 * `capsule-feed-demo-ar-deck.adoc` contains `:revealjs_direction: rtl`, which
 * the slider plugin wires to `revealjsOptions.setRightToLeft(true)` at build
 * time. The test loads the pre-generated HTML — no GradleRunner, no isolated
 * JRuby (root cause diagnosed in session 023).
 *
 * Pipeline:
 *  1. Pre-generated `capsule-feed-demo-ar-deck.html` served via HTTP.
 *  2. Playwright-jvm opens the page and extracts a [SlideRenderData] snapshot.
 *  3. Delegates to [RtlSlideAssertion.assertAll] for P0/P1 validation.
 *
 * Assertions (delegated to RtlSlideAssertion):
 * - P0_RTL_CONFIG  — Reveal.js JS config contains `rtl: true`
 * - P0_RTL_CLASS   — `.reveal` has the `rtl` class (applied at runtime)
 * - P0_NAV         — the "next" navigation control is on the left
 * - P1_OVERFLOW    — slide bounding box fits within viewport width
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class RtlPlaywrightFunctionalTest {

    companion object {
        private val support = PlaywrightFixtureSupport()

        @BeforeAll
        @JvmStatic
        fun launchBrowser() = support.launchBrowser()

        @AfterAll
        @JvmStatic
        fun closeBrowser() = support.closeBrowser()
    }

    @Test
    fun `pre-generated Arabic RTL deck renders in Right-To-Left mode`() {
        val fixtureDir = resolveFixtureDir("playwright.rtl.fixtures.dir")
        val htmlFile = fixtureDir.resolve("capsule-feed-demo-ar-deck.html")
        assertThat(htmlFile.toFile().exists())
            .`as`("RTL fixture HTML must exist — run './gradlew generatePlaywrightFixtures -Planguage=ar' in the root project: $htmlFile")
            .isTrue()

        support.withPage(fixtureDir, "capsule-feed-demo-ar-deck.html", port = 4336) { page ->

            // Wait for Reveal.js to initialise and apply the `.rtl` class at runtime.
            // Reveal.js applies RTL classes asynchronously after DOM ready.
            page.waitForFunction(
                """() => {
                    const reveal = document.querySelector('.reveal');
                    return reveal && (reveal.classList.contains('rtl') || reveal.classList.contains('ready'));
                }"""
            )

            val revealRtlConfig = page.evaluate(
                """() => {
                    const scripts = document.querySelectorAll('script');
                    for (const s of scripts) {
                        if (s.textContent && s.textContent.includes('rtl: true')) return true;
                    }
                    return false;
                }"""
            ) as Boolean

            val revealHasRtlClass = page.evalOnSelector(
                ".reveal",
                "el => el.classList.contains('rtl')"
            ) as Boolean

            val navNextLeft = page.locator(".reveal .controls .navigate-left").count() > 0

            val firstSlide = page.locator(".reveal .slides section").first()
            val slideBox = firstSlide.boundingBox()
            assertThat(slideBox).`as`("Slide bounding box should exist").isNotNull()
            val viewport = page.viewportSize()
            assertThat(viewport).`as`("Viewport should be set").isNotNull()

            val screenshotPath = fixtureDir.resolve("rtl-screenshot.png")
            Files.deleteIfExists(screenshotPath)
            page.screenshot(
                com.microsoft.playwright.Page.ScreenshotOptions()
                    .setPath(screenshotPath)
                    .setFullPage(false)
            )

            val renderData = SlideRenderData(
                revealRtlConfig = revealRtlConfig,
                revealHasRtlClass = revealHasRtlClass,
                navNextLeft = navNextLeft,
                viewportWidth = viewport!!.width,
                slideBoxX = slideBox!!.x,
                slideBoxWidth = slideBox.width,
            )

            val assertionResult = RtlSlideAssertion.assertAll(renderData)

            assertThat(assertionResult.passed)
                .`as`("RTL assertions should all pass. Failures: ${assertionResult.failures}")
                .isTrue()

            assertThat(screenshotPath.toFile().length())
                .`as`("RTL screenshot should be non-trivial (> 10 KB)")
                .isGreaterThan(10_000)
        }
    }

    private fun resolveFixtureDir(property: String): Path {
        val dir = System.getProperty(property)
            ?: error("System property '$property' not set — run './gradlew test'")
        return Path.of(dir).toAbsolutePath().normalize()
    }
}