package slider

import com.microsoft.playwright.assertions.PlaywrightAssertions
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import java.nio.file.Files
import java.nio.file.Path

/**
 * E2E Playwright-jvm test validating that a Reveal.js deck generated by
 * the slider plugin renders correctly in a headless browser.
 *
 * Architecture (session 034):
 * The HTML fixture is pre-generated by the root project's `asciidoctorRevealJs`
 * task (real Gradle home, JRuby gem present) and served via a local HTTP
 * server. This decouples visual validation from GradleRunner, which creates
 * an isolated Gradle user home where JRuby cannot find the asciidoctor-revealjs
 * gem (root cause diagnosed in session 023).
 *
 * Fixture: `capsule-feed-demo-en-deck.html` (LTR, English, 5 slides with
 * speaker notes). Located under `build/docs/asciidocRevealJs/` of the
 * slider-gradle root project.
 *
 * Assertions:
 * - Page title matches the deck header
 * - `.reveal .slides` structure is present
 * - First slide is visible
 * - An h2 heading is visible
 * - Slide bounding box fits within the viewport
 * - Screenshot is non-trivial (> 10 KB)
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class SliderPlaywrightE2eTest {

    companion object {
        private val support = PlaywrightFixtureSupport()

        @BeforeAll
        @JvmStatic
        fun launchBrowser() = support.launchBrowser()

        @AfterAll
        @JvmStatic
        fun closeBrowser() = support.closeBrowser()
    }

    @Test
    fun `pre-generated LTR deck renders correctly in Playwright`() {
        val fixtureDir = resolveFixtureDir("playwright.ltr.fixtures.dir")
        val htmlFile = fixtureDir.resolve("capsule-feed-demo-en-deck.html")
        assertThat(htmlFile.toFile().exists())
            .`as`("LTR fixture HTML must exist — run './gradlew generatePlaywrightFixtures' in the root project: $htmlFile")
            .isTrue()

        support.withPage(fixtureDir, "capsule-feed-demo-en-deck.html") { page ->

            val screenshotPath = fixtureDir.resolve("e2e-screenshot.png")
            Files.deleteIfExists(screenshotPath)
            page.screenshot(
                com.microsoft.playwright.Page.ScreenshotOptions()
                    .setPath(screenshotPath)
                    .setFullPage(false)
            )

            PlaywrightAssertions.assertThat(page).hasTitle("Capsule Feed Demo (English)")

            val firstSlide = page.locator(".reveal .slides section").first()
            PlaywrightAssertions.assertThat(firstSlide).isVisible()

            val h2 = page.locator(".reveal .slides section h2").first()
            PlaywrightAssertions.assertThat(h2).isVisible()

            val slideBox = firstSlide.boundingBox()
            assertThat(slideBox).`as`("Slide bounding box should exist").isNotNull()
            val viewport = page.viewportSize()
            assertThat(viewport).`as`("Viewport should be set").isNotNull()

            assertThat(slideBox!!.x)
                .`as`("Slide left edge should be >= 0")
                .isGreaterThanOrEqualTo(0.0)
            assertThat(slideBox.y)
                .`as`("Slide top edge should be >= 0")
                .isGreaterThanOrEqualTo(0.0)
            assertThat(slideBox.x + slideBox.width)
                .`as`("Slide right edge should fit within viewport width (${viewport!!.width})")
                .isLessThanOrEqualTo(viewport.width.toDouble())
            assertThat(slideBox.y + slideBox.height)
                .`as`("Slide bottom edge should fit within viewport height (${viewport.height})")
                .isLessThanOrEqualTo(viewport.height.toDouble())

            assertThat(screenshotPath.toFile().length())
                .`as`("Screenshot should be non-trivial (> 10 KB)")
                .isGreaterThan(10_000)
        }
    }

    private fun resolveFixtureDir(property: String): Path {
        val dir = System.getProperty(property)
            ?: error("System property '$property' not set — run './gradlew test'")
        return Path.of(dir).toAbsolutePath().normalize()
    }
}