package slider.translation

import contracts.i18n.LanguageCatalog
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import slider.DeckContext
import slider.SliderConfig.yamlMapper
import java.io.File
import java.util.stream.Stream

/**
 * Dogfooding unit test — validates the translated deck files generated by
 * `translateDeck` (S-030, US-5.6) for the 3 demo decks (fr/en/ar).
 *
 * Each source deck was translated into the 9 other supported languages,
 * producing 27 `.adoc` files + 27 `deck-context.yml` files (54 total) in
 * `<repo-root>/slides/misc/`.
 *
 * This test verifies:
 * - Every translated `.adoc` file exists and is non-empty.
 * - Every translated `.adoc` preserves AsciiDoc structure (title `=`, section `==`,
 *   speaker notes `[NOTE.speaker]`, at least one `[%step]` list).
 * - Every translated `deck-context.yml` parses and has the correct `languageCode`.
 * - The `outputFile` in each translated context points to the matching `.adoc`.
 */
class TranslatedDemoDeckTest {

    companion object {
        private val sourceCodes = listOf("fr", "en", "ar")
        private val targetCodes = LanguageCatalog.supportedCodes().toList()

        @JvmStatic
        fun sourceTargetPairs(): Stream<Arguments> =
            sourceCodes.stream().flatMap { src ->
                targetCodes.stream()
                    .filter { it != src }
                    .map { tgt -> Arguments.of(src, tgt) }
            }

        @JvmStatic
        fun sourceCodesProvider(): Stream<Arguments> =
            sourceCodes.stream().map { Arguments.of(it) }
    }

    @ParameterizedTest
    @MethodSource("sourceTargetPairs")
    fun `translated adoc file should exist and be non-empty for each source-target pair`(
        source: String,
        target: String,
    ) {
        val adoc = translatedAdoc(source, target)
        assertThat(adoc.exists())
            .withFailMessage("Translated adoc not found: ${adoc.name}")
            .isTrue()
        assertThat(adoc.readText().trim().isNotEmpty())
            .withFailMessage("Translated adoc is empty: ${adoc.name}")
            .isTrue()
    }

    @ParameterizedTest
    @MethodSource("sourceTargetPairs")
    fun `translated adoc should preserve asciidoc structure with title and sections`(
        source: String,
        target: String,
    ) {
        val content = translatedAdoc(source, target).readText()
        assertThat(content).contains("=")
        assertThat(content).contains("==")
        assertThat(content).contains("[NOTE.speaker]")
        assertThat(content).contains("[%step]")
    }

    @ParameterizedTest
    @MethodSource("sourceTargetPairs")
    fun `translated adoc should preserve revealjs attributes`(
        source: String,
        target: String,
    ) {
        val content = translatedAdoc(source, target).readText()
        assertThat(content).contains(":revealjs_theme:")
        assertThat(content).contains(":revealjs_width:")
        assertThat(content).contains(":revealjs_height:")
    }

    @ParameterizedTest
    @MethodSource("sourceTargetPairs")
    fun `translated deck-context should parse with correct languageCode and matching outputFile`(
        source: String,
        target: String,
    ) {
        val ctx = translatedContext(source, target)
        assertThat(ctx.languageCode).isEqualTo(target)
        ctx.requireValidLanguage()

        val adoc = slidesMiscDir().resolve(ctx.outputFile)
        assertThat(adoc.exists())
            .withFailMessage("outputFile '${ctx.outputFile}' does not resolve to existing adoc")
            .isTrue()
    }

    @ParameterizedTest
    @MethodSource("sourceCodesProvider")
    fun `each source deck should have exactly 9 translated adoc files`(source: String) {
        val translated = slidesMiscDir().listFiles { f ->
            f.name.startsWith("capsule-feed-demo-${source}_") &&
                f.name.endsWith("-deck.adoc")
        } ?: emptyArray()
        assertThat(translated).hasSize(9)
    }

    @ParameterizedTest
    @MethodSource("sourceCodesProvider")
    fun `each source deck should have exactly 9 translated context files`(source: String) {
        val translated = slidesMiscDir().listFiles { f ->
            f.name.startsWith("capsule-feed-demo-${source}_") &&
                f.name.endsWith("-deck-context.yml")
        } ?: emptyArray()
        assertThat(translated).hasSize(9)
    }

    @Test
    fun `all 27 translated adoc files should exist across 3 sources`() {
        val allAdoc = slidesMiscDir().listFiles { f ->
            f.name.matches(Regex("capsule-feed-demo-(fr|en|ar)_[a-z]{2}-deck\\.adoc"))
        } ?: emptyArray()
        assertThat(allAdoc).hasSize(27)
    }

    @Test
    fun `all 27 translated context files should exist across 3 sources`() {
        val allCtx = slidesMiscDir().listFiles { f ->
            f.name.matches(Regex("capsule-feed-demo-(fr|en|ar)_[a-z]{2}-deck-context\\.yml"))
        } ?: emptyArray()
        assertThat(allCtx).hasSize(27)
    }

    @Test
    fun `rtl target decks ar and ur should contain revealjs_direction rtl attribute`() {
        listOf("fr", "en", "ar").forEach { source ->
            listOf("ar", "ur").forEach { target ->
                if (source == target) return@forEach
                val content = translatedAdoc(source, target).readText()
                assertThat(content)
                    .withFailMessage("RTL deck $source→$target should have :revealjs_direction: rtl")
                    .contains(":revealjs_direction: rtl")
            }
        }
    }

    private fun translatedAdoc(source: String, target: String): File =
        slidesMiscDir().resolve("capsule-feed-demo-${source}_${target}-deck.adoc")

    private fun translatedContext(source: String, target: String): DeckContext {
        val file = slidesMiscDir().resolve("capsule-feed-demo-${source}_${target}-deck-context.yml")
        assertThat(file.exists())
            .withFailMessage("Translated context not found: ${file.name}")
            .isTrue()
        return yamlMapper.readValue(file, DeckContext::class.java)
    }

    private fun slidesMiscDir(): File =
        File(resolveRepoRoot(), "slides/misc")
            .takeIf { it.exists() }
            ?: File(resolveRepoRoot(), "foundry/public/slider-gradle/slides/misc")

    private fun resolveRepoRoot(): File {
        var dir = File(".").absoluteFile
        while (dir != null && dir.parentFile != null) {
            if (File(dir, "slides/misc/capsule-feed-demo-fr-deck.adoc").exists()) return dir
            if (File(dir, "foundry/public/slider-gradle/slides/misc/capsule-feed-demo-fr-deck.adoc").exists()) return dir
            dir = dir.parentFile
        }
        return File(".").absoluteFile
    }
}