package slider.steps

import contracts.i18n.LanguageCatalog
import io.cucumber.java8.En
import org.assertj.core.api.Assertions.assertThat
import slider.DeckContext
import slider.SliderConfig.yamlMapper
import java.io.File

/**
 * Cucumber steps for the deck translation dogfood feature
 * (14_deck_translation_dogfood.feature).
 *
 * These steps validate the real translated files generated by
 * `translateDeck` for the 3 demo decks (fr/en/ar) across all
 * 10 supported languages.
 */
class DeckTranslationDogfoodSteps : En {

    private var currentContext: DeckContext? = null
    private var currentAdoc: String? = null

    private fun slidesMiscDir(): File = resolveSlidesMiscDir()

    init {

        Given("the demo deck context for {string} exists") { code: String ->
            val file = demoContextFile(code)
            assertThat(file.exists())
                .withFailMessage("Demo deck-context not found: ${file.absolutePath}")
                .isTrue()
            currentContext = yamlMapper.readValue(file, DeckContext::class.java)
        }

        Given("the source deck {string} has been translated") { source: String ->
            val translated = slidesMiscDir().listFiles { f ->
                f.name.startsWith("capsule-feed-demo-${source}_") &&
                    f.name.endsWith("-deck.adoc")
            } ?: emptyArray()
            assertThat(translated)
                .withFailMessage("No translated adoc files found for source '$source'")
                .isNotEmpty
        }

        Given("the translated adoc from {string} to {string} exists") { source: String, target: String ->
            val file = slidesMiscDir().resolve("capsule-feed-demo-${source}_${target}-deck.adoc")
            assertThat(file.exists())
                .withFailMessage("Translated adoc not found: ${file.name}")
                .isTrue()
            currentAdoc = file.readText()
        }

        Given("the translated context from {string} to {string} exists") { source: String, target: String ->
            val file = slidesMiscDir().resolve("capsule-feed-demo-${source}_${target}-deck-context.yml")
            assertThat(file.exists())
                .withFailMessage("Translated context not found: ${file.name}")
                .isTrue()
            currentContext = yamlMapper.readValue(file, DeckContext::class.java)
        }

        Then("the context language code should be {string}") { expectedCode: String ->
            assertThat(currentContext).isNotNull()
            assertThat(currentContext!!.languageCode).isEqualTo(expectedCode)
        }

        Then("the context output file should exist as adoc") {
            assertThat(currentContext).isNotNull()
            val adoc = slidesMiscDir().resolve(currentContext!!.outputFile)
            assertThat(adoc.exists())
                .withFailMessage("Output adoc not found: ${adoc.absolutePath}")
                .isTrue()
        }

        Then("the adoc should contain a title starting with {string}") { prefix: String ->
            assertThat(currentAdoc).isNotNull()
            val firstLine = currentAdoc!!.lines().firstOrNull { it.isNotBlank() }
            assertThat(firstLine).startsWith(prefix)
        }

        Then("the adoc should contain a section header {string}") { fragment: String ->
            assertThat(currentAdoc).isNotNull()
            assertThat(currentAdoc!!).contains(fragment)
        }

        Then("the adoc should contain {string}") { fragment: String ->
            assertThat(currentAdoc).isNotNull()
            assertThat(currentAdoc!!).contains(fragment)
        }

        Then("the adoc should not contain {string}") { fragment: String ->
            assertThat(currentAdoc).isNotNull()
            assertThat(currentAdoc!!).doesNotContain(fragment)
        }

        Then("the adoc should be non-empty") {
            assertThat(currentAdoc).isNotNull()
            assertThat(currentAdoc!!.trim().isNotEmpty()).isTrue()
        }

        Then("there should be {int} translated adoc files for source {string}") { count: Int, source: String ->
            val files = slidesMiscDir().listFiles { f ->
                f.name.startsWith("capsule-feed-demo-${source}_") &&
                    f.name.endsWith("-deck.adoc")
            } ?: emptyArray()
            assertThat(files).hasSize(count)
        }

        Then("there should be {int} translated context files for source {string}") { count: Int, source: String ->
            val files = slidesMiscDir().listFiles { f ->
                f.name.startsWith("capsule-feed-demo-${source}_") &&
                    f.name.endsWith("-deck-context.yml")
            } ?: emptyArray()
            assertThat(files).hasSize(count)
        }

        Then("there should be {int} translated adoc files total") { total: Int ->
            val files = slidesMiscDir().listFiles { f ->
                f.name.matches(Regex("capsule-feed-demo-(fr|en|ar)_[a-z]{2}-deck\\.adoc"))
            } ?: emptyArray()
            assertThat(files).hasSize(total)
        }

        Then("there should be {int} translated context files total") { total: Int ->
            val files = slidesMiscDir().listFiles { f ->
                f.name.matches(Regex("capsule-feed-demo-(fr|en|ar)_[a-z]{2}-deck-context\\.yml"))
            } ?: emptyArray()
            assertThat(files).hasSize(total)
        }
    }

    private fun demoContextFile(code: String): File =
        slidesMiscDir().resolve("capsule-feed-demo-$code-deck-context.yml")

    private fun resolveSlidesMiscDir(): File {
        val dir = resolveRepoRoot()
        val direct = File(dir, "slides/misc")
        if (direct.exists()) return direct
        val nested = File(dir, "foundry/public/slider-gradle/slides/misc")
        if (nested.exists()) return nested
        error("slides/misc directory not found from ${dir.absolutePath}")
    }

    private fun resolveRepoRoot(): File {
        var dir = File(".").absoluteFile
        while (dir != null && dir.parentFile != null) {
            if (File(dir, "slides/misc/capsule-feed-demo-fr-deck.adoc").exists()) return dir
            if (File(dir, "foundry/public/slider-gradle/slides/misc/capsule-feed-demo-fr-deck.adoc").exists()) return dir
            dir = dir.parentFile
        }
        return File(".").absoluteFile
    }
}