package slider

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import slider.content.ContentAssertionResult
import slider.content.ContentRenderAssertion
import java.nio.file.Path

/**
 * Playwright-jvm functional test validating that a pre-generated LTR
 * Reveal.js deck renders content correctly: text blocks fit within the
 * viewport, speaker notes are present in the DOM, body font is readable,
 * and the title/body contrast ratio meets WCAG AA.
 *
 * Architecture (session 053 — SLD-10.5):
 * The HTML fixture is pre-generated by the root project's
 * `generatePlaywrightFixtures` task (real Gradle home, JRuby gem present).
 * The test loads the pre-generated LTR English demo deck
 * `capsule-feed-demo-en-deck.html` — no GradleRunner, no isolated JRuby
 * (root cause diagnosed in session 023).
 *
 * Pipeline:
 *  1. Pre-generated `capsule-feed-demo-en-deck.html` served via HTTP (port 4337).
 *  2. [ContentPlaywrightAdapter] extracts a [ContentRenderData] snapshot.
 *  3. Delegates to [ContentRenderAssertion.assertAll] for P0/P1 validation.
 *
 * Assertions (delegated to ContentRenderAssertion):
 * - P0_OVERFLOW      — no real text block overflows the viewport
 * - P0_MISSING_NOTES — the speaker note is rendered in the DOM
 * - P1_FONT_SIZE     — the computed body font size is >= 14 CSS px
 * - P1_CONTRAST      — the computed contrast ratio is >= 4.5 (WCAG AA)
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ContentPlaywrightFunctionalTest {

    companion object {
        private const val PORT = 4337
        private val support = PlaywrightFixtureSupport()

        @BeforeAll
        @JvmStatic
        fun launchBrowser() = support.launchBrowser()

        @AfterAll
        @JvmStatic
        fun closeBrowser() = support.closeBrowser()
    }

    @Test
    fun `pre-generated LTR deck renders content within viewport with readable fonts`() {
        val fixtureDir = resolveFixtureDir("playwright.ltr.fixtures.dir")
        val htmlFile = "capsule-feed-demo-en-deck.html"
        assertThat(fixtureDir.resolve(htmlFile).toFile().exists())
            .`as`("LTR fixture HTML must exist — run './gradlew generatePlaywrightFixtures' in the root project: ${fixtureDir.resolve(htmlFile)}")
            .isTrue()

        support.withPage(fixtureDir, htmlFile, port = PORT) { page ->
            val renderData = ContentPlaywrightAdapter.extract(page, slideIndex = 0)
            val result = ContentRenderAssertion.assertAll(renderData)

            assertThat(result)
                .`as`("Content render assertions should all pass. Failures: ${(result as? ContentAssertionResult.Failed)?.failures ?: "none"}")
                .isInstanceOf(ContentAssertionResult.Passed::class.java)
        }
    }

    private fun resolveFixtureDir(property: String): Path {
        val dir = System.getProperty(property)
            ?: error("System property '$property' not set — run './gradlew :slider:test'")
        return Path.of(dir).toAbsolutePath().normalize()
    }
}