package slider

import com.microsoft.playwright.Browser
import com.microsoft.playwright.BrowserContext
import com.microsoft.playwright.Playwright
import com.microsoft.playwright.assertions.PlaywrightAssertions
import org.assertj.core.api.Assertions.assertThat
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import org.junit.jupiter.api.io.TempDir
import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.absolutePathString
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * E2E test Playwright-jvm pour le pipeline slider-gradle.
 *
 * 3 assertions :
 * - generateSlides BUILD SUCCESSFUL
 * - index.html contient reveal.js (.reveal .slides)
 * - Screenshot > 10 KB (page non-vide)
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class SliderPlaywrightE2eTest {

    private lateinit var playwright: Playwright
    private lateinit var browser: Browser

    @BeforeAll
    fun launchBrowser() {
        playwright = Playwright.create()
        browser = playwright.chromium().launch(
            com.microsoft.playwright.BrowserType.LaunchOptions()
                .setHeadless(true)
                .setArgs(listOf("--no-sandbox", "--disable-gpu"))
        )
    }

    @AfterAll
    fun closeBrowser() {
        browser.close()
        playwright.close()
    }

    @Test
    fun `generateSlides then Playwright assert reveal js content`(@TempDir tempDir: Path) {
        // ── 1. Préparer le projet Gradle consommateur ──────────────────
        val settings = tempDir.resolve("settings.gradle.kts")
        settings.writeText("""
            pluginManagement {
                repositories { mavenLocal(); gradlePluginPortal(); mavenCentral() }
            }
            rootProject.name = "slider-e2e-test"
        """.trimIndent())

        val build = tempDir.resolve("build.gradle.kts")
        build.writeText("""
            plugins {
                id("org.asciidoctor.jvm.revealjs.classic") version "5.0.0-alpha.1"
                id("education.cccp.slider") version "0.0.6"
            }
            slider { configPath = file("slides-context.yml").absolutePath }
        """.trimIndent())

        val configYml = tempDir.resolve("slides-context.yml")
        configYml.writeText("""
            presentation:
              title: "E2E Test Playwright"
              subtitle: "Slider Gradle Plugin"
              author:
                name: "CCCP Education"
                email: "cccp.education@gmail.com"
            revealjs:
              theme: "black"
              transition: "slide"
              slideNumber: true
              history: true
            slides:
              - src: "intro.adoc"
                title: "Introduction"
        """.trimIndent())

        val slidesDir = tempDir.resolve("slides").resolve("misc")
        slidesDir.createDirectories()
        val introAdoc = slidesDir.resolve("intro.adoc")
        introAdoc.writeText("""
            = E2E Test Playwright
            :revealjs_theme: black
            :revealjs_transition: slide
            :toc: auto

            == Playwright E2E

            This slide was generated by the slider Gradle plugin
            and validated by a Playwright-jvm end-to-end test.

            === Features Tested

            * Reveal.js rendering
            * Playwright screenshot capture
            * CI readiness
        """.trimIndent())

        // ── 2. Exécuter generateSlides via mavenLocal ─────────────────
        // withPluginClasspath() n'inclut pas les dépendances transitives
        // (asciidoctor-gradle) → on utilise mavenLocal pour résoudre le
        // plugin slider publié (avec toutes ses dépendances).
        val result = GradleRunner.create()
            .withProjectDir(tempDir.toFile())
            .withArguments("asciidoctorRevealJs", "--stacktrace")
            .forwardOutput()
            .build()

        assertThat(result.task(":asciidoctorRevealJs")?.outcome)
            .`as`("asciidoctorRevealJs should succeed")
            .isEqualTo(org.gradle.testkit.runner.TaskOutcome.SUCCESS)

        // ── 3. Vérifier le HTML généré — index.html (Reveal.js) ──
        val slideHtml = tempDir.resolve("slides/misc/index.html").toFile()
        assertThat(slideHtml.exists()).`as`("index.html should exist in slides/misc/").isTrue()
        assertThat(slideHtml.length()).`as`("index.html should not be empty").isGreaterThan(100)

        // ── 4. Playwright — ouvrir le slide et screenshot ─────────────
        val fileUrl = "file://${slideHtml.absolutePath}"
        val context: BrowserContext = browser.newContext()
        val page = context.newPage()
        page.navigate(fileUrl)
        page.waitForSelector(".reveal .slides")

        val screenshotPath = tempDir.resolve("build/e2e-screenshot.png")
        Files.createDirectories(screenshotPath.parent)
        page.screenshot(
            com.microsoft.playwright.Page.ScreenshotOptions()
                .setPath(screenshotPath)
                .setFullPage(false)
        )

        // ── 5. Assertions Playwright — UX/UI ────────────────────────────
        PlaywrightAssertions.assertThat(page).hasTitle("E2E Test Playwright")

        val slideElement = page.locator(".reveal .slides section")
        PlaywrightAssertions.assertThat(slideElement).isVisible()

        val h2 = page.locator(".reveal .slides section section h2")
        PlaywrightAssertions.assertThat(h2).isVisible()

        // UX/UI : tout le contenu de la slide est visible dans le viewport
        val slideBox = slideElement.boundingBox()
        assertThat(slideBox).`as`("Slide bounding box should exist").isNotNull()
        val viewport = page.viewportSize()
        assertThat(viewport).`as`("Viewport should be set").isNotNull()

        assertThat(slideBox!!.x).`as`("Slide left edge should be >= 0").isGreaterThanOrEqualTo(0.0)
        assertThat(slideBox.y).`as`("Slide top edge should be >= 0").isGreaterThanOrEqualTo(0.0)
        assertThat(slideBox.x + slideBox.width)
            .`as`("Slide right edge should fit within viewport width (${viewport!!.width})")
            .isLessThanOrEqualTo(viewport.width.toDouble())
        assertThat(slideBox.y + slideBox.height)
            .`as`("Slide bottom edge should fit within viewport height (${viewport.height})")
            .isLessThanOrEqualTo(viewport.height.toDouble())

        // Screenshot visible proof

        assertThat(screenshotPath.toFile().length())
            .`as`("Screenshot should be non-trivial (> 10 KB)")
            .isGreaterThan(10_000)

        context.close()
    }
}
